GET http://localhost:3000/peliculas

###

POST http://localhost:3000/peliculas
Content-Type: application/json

{
    "title": "Star Wars 2",
    "release_year": 2002,
    "locations": "Escocia",
    "production_company": "Lucasfilms",
    "director": "George Lucas",
    "writer": "Dave Filoni, George Lucas",
    "actor 1": "Ewan MccGregor",
    "actor_2": "Hayden Christensen",
    "actor_3": "Natalie Portman"
}